### ISSUE TITLE
owncloud webdav

### ISSUE THREAD

**Issue by kerimlcr** [designerror/webdav-client-python#18]
Hi,
I tried your client for owncloud
upload_sync worked smoothly but download_sync ...
I gave the output. What could cause this
 
>c.download_sync(remote_path="http://localhost/owncloud/remote.php/webdav/sync/", local_path="/home/kerim/sync")
___
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kerim/.local/lib/python2.7/site-packages/webdav/client.py", line 417, in download_sync
    self.download(local_path=local_path, remote_path=remote_path)
  File "/home/kerim/.local/lib/python2.7/site-packages/webdav/client.py", line 358, in download
    if self.is_dir(urn.path()):
  File "/home/kerim/.local/lib/python2.7/site-packages/webdav/client.py", line 845, in is_dir
    raise RemoteResourceNotFound(remote_path)
webdav.exceptions.RemoteResourceNotFound: Remote resource: /http:/localhost/owncloud/remote.php/webdav/sync/ not found
___

**Comment by Prince-Leto** [comment]
In ownCloud, webdav is accessible via `/remote.php/webdav`

And it's tempting to use ownCloud with this configuration:

**Comment by Prince-Leto** [comment]
In ownCloud, webdav is accessible via /remote.php/webdav

And it's tempting to use ownCloud with this configuration:
```
options = {
 'webdav_hostname': "https://<hostname>/remote.php/webdav",
 'webdav_login': "login",
 'webdav_password': "password"
}
```

But in fact you need to use the `root` option, like this:
```
options = {
 'webdav_hostname': "https://<hostname>",
 'webdav_login': "login",
 'webdav_password': "password",
 'root': "/remote.php/webdav"
}
```

Is that your issue?

**Comment by designerror** [comment]
I'm using `webdav_root option`
```python
options = {
 'webdav_hostname': "https://<hostname>",
 'webdav_login': "login",
 'webdav_password': "password",
 'webdav_root': "/remote.php/webdav"
}```

**Comment by Nayar** [comment]
Having the same issue :(

**Comment by krowvin** [comment]
Be sure **if you are using a subdirectory** to place that in the webdav_root as well: 

For example, say your full webdav url is `https://nas.domain.com/cloud/remote.php/webdav/`

Your options would look like this:
```
options = {
 'webdav_hostname': "https://nas.domain.com",
 'webdav_login': "login",
 'webdav_password': "password",
 'webdav_root': "/cloud/remote.php/webdav"
}
```
